name: Generate static website with Hugo
on: push
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
            submodules: 'recursive'

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.88.1"
          extended: true
          
      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.ACTIONS_TOKEN }}
          user_name: asfdfdfd
          user_email: asfdfdfd@asfdfdfd.com
          publish_branch: gh-pages
          cname: nesgames.asfdfdfd.com